version: "3.8"

services:
  bucket-manager-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
